language: perl
dist: trusty
install:
  - sudo apt-get install vim
  - curl -sL https://git.io/cpm | perl - install -g --show-build-log-on-failure
  - git fetch origin p5-corpus-ng:origin/p5-corpus-ng
  - vim --version
script:
  - make test
branches:
  except:
    - p5-corpus
